# Generated by Django 3.2.1 on 2023-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
