# Generated by Django 3.2.1 on 2023-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_questionnaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
