# Generated by Django 3.2.1 on 2023-04-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerTime',
            field=models.IntegerField(default=0),
        ),
    ]
