# Generated by Django 3.2.1 on 2023-04-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_question_answertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='countdown_time',
            new_name='countdownTime',
        ),
    ]
