# Generated by Django 3.2.1 on 2023-04-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_rename_countdown_time_game_countdowntime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='public_id',
            new_name='publicId',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='question_no',
            new_name='questionNo',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='created_at',
        ),
        migrations.AddField(
            model_name='guess',
            name='guess_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
