# Generated by Django 3.2.1 on 2023-04-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_game_publicid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=965331, unique=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
