# Generated by Django 3.2.1 on 2023-04-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20230402_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=554968, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
