# Generated by Django 3.2.1 on 2023-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20230402_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=586480, unique=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess_id',
            field=models.IntegerField(default=257812, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.IntegerField(default=545023, primary_key=True, serialize=False, unique=True),
        ),
    ]
