# Generated by Django 3.2.1 on 2023-04-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20230402_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=259838, unique=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
