# Generated by Django 3.2.1 on 2023-04-10 10:18

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20230407_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='game',
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='countdownTime',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerTime',
            field=models.IntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Guess',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
