# Generated by Django 3.2.1 on 2023-04-10 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20230410_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Anonymous', max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('uuidP', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.game')),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.answer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.question')),
            ],
        ),
    ]
